# syntax = docker/dockerfile:1.0-experimental
ARG base
FROM $base

RUN echo "hello1" > child-1.txt
RUN echo "hello2" > child-2.txt
RUN echo "hello3" > child-3.txt
RUN echo "hello4" > child-4.txt

RUN --mount=type=secret,id=ssh_key,dst=secret1.txt echo "foo" > child-secret.txt

RUN echo "hello2" > hello-child4.txt

COPY entrypoint.sh entrypoint.sh


